[package]
name = "fuzzymatch-rs"
version = "0.1.0"
edition = "2018"

[lib]
name = "fuzzymatch_rs"
crate-type = ["cdylib"]

[dependencies.rff]
version = "0.3.0"

[dependencies.pyo3]
version = "0.8.3"
features = ["extension-module"]
